### ISSUE TITLE
Reducing the size of files by eliminating intermediate steps and cuts

### ISSUE THREAD

**Issue by thiagofelicissimo** [Deducteam/hol2dk#52]
I'm currently considering the possibility of forking this to make an output to test the performances of my new [bidirectional framework](https://github.com/thiagofelicissimo/BiTTs) (which features erased arguments, that should allow for smaller proofs and faster checking). While playing with the tool, I noticed that it outputs many intermediate proofs steps, and even silly ones like 
```
def thm_10 : q : El bool -> p : El bool -> h1 : Prf (term3 q p) -> Prf (term3 q p) := 
   q : El bool => p : El bool => h1 : Prf (term3 q p) => h1.
def thm_27 : q : El bool -> Prf (eq bool q q) := q : El bool => REFL bool q.
```
This probably can reduce some of the advantages of erased arguments, because they let you write `refl` instead of `refl bool q`, but if you instead define `thm_27` like above you will have to write `thm_27 q`, whereas you could write just `refl`. 

I decided to do a small test with dkmeta to see what would be the impact of inlining these intermediate steps. The starting point is the output of the tool in dk until ind_defs (going beyond this was making dkmeta take too long). By making the intermediate proof steps non-opaque (requires changing the `thm thm_n` to `def thm_n`) and running dkmeta, it reduces all the intermediate uses of `type_n`, `term_n` and `thm_n`. This increases the file size from 1.9mb (the file we start with) to 56mb. Then, by deleting from the file all of the `type_n`, `term_n` and `thm_n` (which are of no use anymore) and preserving only the named theorems, the size goes down to 4.6mb, which is more comparable to the initial one.

Then, I repeated the same process, but adding to the starting file the following rules allowing to eliminate some cuts --- note that in order to add the first two I removed the definitions of TRANS and SYM. 
```
[e] TRANS _ _ _ _ (REFL _ _) e --> e.
[A, x] SYM A x _ (REFL _ _) --> REFL A x.
[P, Q, P', Q', pq, qp, p] EQ_MP P Q (prop_ext P' Q' pq qp) p --> pq p.
[P, P', P'', p] EQ_MP P P' (REFL bool P'') p --> p.
[A, B, s, s', u, u', C, s'', A'', u''] MK_COMB A B s s' u u' (REFL C s'') (REFL A'' u'') --> REFL B (s u).
[A, B, s, t, u, u', A', B', s', t', p', A'', u''] MK_COMB A B s t u u' (fun_ext A' B' s' t' p') (REFL A'' u'') --> p' u.
[A, B, A', B', a, b] and_elim1 A B (and_intro A' a B' b) --> a.
[A, B, A', B', a, b] and_elim2 A B (and_intro A' a B' b) --> b.
[A, B, A', B', a, P, pa, pb] or_elim A B (or_intro1 A' a B') P pa pb --> pa a.
[A, B, A', B', b, P, pa, pb] or_elim A B (or_intro2 A' B' b) P pa pb --> pb b.
[A, B, A', B', a, b, P, p] ex_elim A B (ex_intro A' B' a b) P p --> p a b.
```
Now, when doing the same process as before, the size of the file goes down from 1.9mb to 266kb !

So my question is : have you considered the idea of eliminating intermediate steps and cuts in the translation ? Maybe that the loss in sharing could be a bit too severe in some cases, but then it might be possible to develop a simple heuristic to detect when a proof step is too silly (like thm_10 above) and can be safely inlined without making the file bigger.

The files : [files.zip](https://github.com/Deducteam/hol2dk/files/13252700/files.zip)

**Comment by fblanqui** [comment]
Hi Thiago. Thanks for your experiment! Yes, I was considering some of the rules you mention but didn't do any experiment yet. See https://github.com/Deducteam/hol2dk/blob/main/TODO.md. It looks interesting. Whether it leads to size reduction on the whole HOL-Light library is unclear though as the beginning of the library is very different from the rest. At the beginning, very foundational things are proved including natural deduction rules. While, later, real mathematical results are proved. But it would be interesting to push the experiment further to check this, at least up to hol.ml entirely, and compute how many times each rule is used. But, as you experimented, dkmeta doesn't seem appropriate for doing this. Instead, this needs to be done on the HOL-Light side when proofs are created.

**Comment by fblanqui** [comment]
This is done in https://github.com/Deducteam/hol2dk/pull/63.

**Comment by thiagofelicissimo** [comment]
Nice! But in my proposal, I had talked about two kinds of simplifications:

1) Eliminate cuts by using the rewrite rules I showed
2) Inline proof steps that are too silly, like `thm_10` and `thm_27` above

I have the impression that your PR does only 1 but not 2, am I wrong?

A second question: why do you not implement all of the rewrite rules above? Is it to avoid introducing beta-redexes, which when reduced could possibly make the term bigger?

**Comment by fblanqui** [comment]
I implement rules at the HOL-Light proof level only. Feel free to propose something to rewrite proofs at the dk level if you want. But it should scale up...

**Comment by fblanqui** [comment]
The size of generated files has been reduced further by not exporting theorems that do not contribute to a named theorem: 60% in the case of hol.ml after proof rewriting! See https://github.com/Deducteam/hol2dk/pull/65. hol_upto_arith can now be checked by coq in 1h only.
